/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.AnggotaPinjamController;
import controllers.SimpananController;
import entities.AnggotaPinjam;
import entities.SessionLogin;
import entities.Simpanan;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gusma
 */
public class AnggotaPinjamView extends javax.swing.JInternalFrame {

    private Connection connection;
    private SessionLogin sessionLogin;
    private AnggotaPinjamController anggotaPinjamController;
    private SimpananController simpananController;

    /**
     * Creates new form AnggotaPinjamView
     */
    public AnggotaPinjamView(Connection connection) {
        this.connection = connection;
        initComponents();
        this.sessionLogin = new SessionLogin();
        this.anggotaPinjamController = new AnggotaPinjamController(connection);
        this.simpananController = new SimpananController(connection);
        labelkaryawan.setText(SessionLogin.getUserLogin());
        bindingTable();
        cekSaldo();
        btnEdit.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAPinjam = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textkdAnggotaP = new javax.swing.JTextField();
        textAnggota = new javax.swing.JTextField();
        textNamaJ = new javax.swing.JTextField();
        textNominal = new javax.swing.JTextField();
        textJangka = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textCariPinjam = new javax.swing.JTextField();
        cmbAnggotaPinjam = new javax.swing.JComboBox<>();
        btnCari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelkaryawan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSaldo = new javax.swing.JTable();

        setClosable(true);
        setTitle("Anggota Pinjam");

        tblAPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAPinjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAPinjam);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Anggota Pinjam"));

        jLabel1.setText("KD AnggotaPinjam");

        jLabel2.setText("KD Anggota");

        jLabel4.setText("Nama Jaminan");

        jLabel6.setText("Nominal Pinjam");

        jLabel7.setText("Jangka Waktu");

        textAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAnggotaActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel5.setText("Bulan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(textJangka, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textkdAnggotaP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNamaJ, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textkdAnggotaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNamaJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textJangka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnEdit))
                .addGap(48, 48, 48))
        );

        cmbAnggotaPinjam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kd_anggotapinjam", "kd_anggota", "nama_jaminan", "tgl_pinjam", "nominal_pinjam", "jangka_waktu" }));

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel3.setText("Kode Karyawan");

        labelkaryawan.setText("jLabel5");

        tblSaldo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblSaldo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbAnggotaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textCariPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCari)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelkaryawan)
                                .addGap(60, 60, 60))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textCariPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbAnggotaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(labelkaryawan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        boolean flag = this.anggotaPinjamController.save( textAnggota.getText(), labelkaryawan.getText(), textNamaJ.getText(), Integer.parseInt(textNominal.getText()), Integer.parseInt(textJangka.getText()));
        String message = "Failed to save data";
        if (flag) {
            message = "succes save";
        }
        JOptionPane.showMessageDialog(this, message, "Allert/Notification", JOptionPane.INFORMATION_MESSAGE);
        bindingTable();
        cekSaldo();
        reset();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void textAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAnggotaActionPerformed

    private void tblAPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAPinjamMouseClicked
        // TODO add your handling code here:
        int row = tblAPinjam.getSelectedRow();

        textkdAnggotaP.setText(tblAPinjam.getValueAt(row, 0).toString());
        textAnggota.setText(tblAPinjam.getValueAt(row, 1).toString());
        textNamaJ.setText(tblAPinjam.getValueAt(row, 2).toString());
        textNominal.setText(tblAPinjam.getValueAt(row, 4).toString());
        textJangka.setText(tblAPinjam.getValueAt(row, 5).toString());
        textNominal.setEnabled(false);
        textJangka.setEnabled(false);
        btnEdit.setEnabled(true);
        btnSave.setEnabled(false);
    }//GEN-LAST:event_tblAPinjamMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:

        String message = "Failed to edit data";
        if (anggotaPinjamController.edit(textkdAnggotaP.getText(), textAnggota.getText(), labelkaryawan.getText(), textNamaJ.getText())) {
            message = "Succes to edit data";
        }
        JOptionPane.showMessageDialog(this, message, "Notification", JOptionPane.ERROR_MESSAGE);
        bindingTable();

        reset();


    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        SearchTable(cmbAnggotaPinjam.getSelectedItem().toString(), textCariPinjam.getText());

    }//GEN-LAST:event_btnCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbAnggotaPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelkaryawan;
    private javax.swing.JTable tblAPinjam;
    private javax.swing.JTable tblSaldo;
    private javax.swing.JTextField textAnggota;
    private javax.swing.JTextField textCariPinjam;
    private javax.swing.JTextField textJangka;
    private javax.swing.JTextField textNamaJ;
    private javax.swing.JTextField textNominal;
    private javax.swing.JTextField textkdAnggotaP;
    // End of variables declaration//GEN-END:variables

    private void SearchTable(String category, String data) {

        String[] header = {"Kode Anggota Pinjam", "Kode Anggota", "nama jaminan", "tgl pinjam", "nominal pinjam", "jangka waktu"};

        DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
        for (AnggotaPinjam anggotaPinjam : anggotaPinjamController.find(category, data)) {
            Object[] region1 = {
                anggotaPinjam.getKdAnggotaP(), anggotaPinjam.getKdAnggota(), anggotaPinjam.getNamaJaminan(), anggotaPinjam.getTglPinjam(), anggotaPinjam.getNominalPinjam(), anggotaPinjam.getJangkaWaktu()
            };
            defaultTableModel.addRow(region1);
        }
        tblAPinjam.setModel(defaultTableModel);
    }

    public void bindingTable() {

        String[] header = {"Kode Anggota Pinjam", "kode Anggota", "Nama jaminan", "tgl pinjam", "nominal pinjam", "jangka waktu"};

        DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
        for (AnggotaPinjam anggotaPinjam : anggotaPinjamController.binding()) {
            Object[] region1 = {
                anggotaPinjam.getKdAnggotaP(), anggotaPinjam.getKdAnggota(), anggotaPinjam.getNamaJaminan(), anggotaPinjam.getTglPinjam(), anggotaPinjam.getNominalPinjam(), anggotaPinjam.getJangkaWaktu()
            };
            defaultTableModel.addRow(region1);
        }
        tblAPinjam.setModel(defaultTableModel);

    }

    public void cekSaldo() {
        String[] header = {"Jumlah Saldo"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
        for (Simpanan simpanan : simpananController.binding()) {
            Object[] region1 = {
                simpanan.getTotalSimpan()
            };
            defaultTableModel.addRow(region1);
        }

        tblSaldo.setModel(defaultTableModel);
    }

    public void reset() {
        textkdAnggotaP.setText("");
        textAnggota.setText("");
        textNamaJ.setText("");
        textNominal.setText("");
        textJangka.setText("");
    }
}
