/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.AnggotaSimpanController;
import controllers.SimpananController;
import entities.AnggotaSimpan;
import entities.SessionLogin;
import entities.Simpanan;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iqbael17
 */
public class AnggotaSimpanView extends javax.swing.JInternalFrame {

    private Connection connection;
    private SessionLogin sessionLogin;
    private AnggotaSimpanController anggotaSimpanController;
    private SimpananController simpananController;

    /**
     * Creates new form AnggotaSImpanView
     */
    public AnggotaSimpanView(Connection connection) {
        this.connection = connection;
        initComponents();
        this.anggotaSimpanController = new AnggotaSimpanController(connection);
        this.simpananController = new SimpananController(connection);
        this.sessionLogin = new SessionLogin();
        lblKaryawan.setText(SessionLogin.getUserLogin());
        btnEdit.setEnabled(false);
        bindingTable();
        cekSaldo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnggotaSimpan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtkdAnggotaSimpan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtkdAnggota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNominal = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        cmbCatagtpinjam = new javax.swing.JComboBox<>();
        txtCariAnggotaSimpan = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblKaryawan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSaldo = new javax.swing.JTable();

        setClosable(true);
        setTitle("Anggota Simpan");

        tblAnggotaSimpan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAnggotaSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAnggotaSimpanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAnggotaSimpan);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Simpanan"));

        jLabel1.setText("Kode Anggota Simpan");

        jLabel2.setText("Kode Anggota");

        jLabel3.setText("Nominal");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtkdAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(txtkdAnggotaSimpan))
                            .addComponent(txtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtkdAnggotaSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtkdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnEdit))
                .addGap(33, 33, 33))
        );

        cmbCatagtpinjam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kd_anggotasimpan", "kd_anggota", "tgl_simpan", "nominal" }));
        cmbCatagtpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCatagtpinjamActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        jLabel4.setText("Kode Karyawan ");

        lblKaryawan.setText("jLabel5");

        tblSaldo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSaldoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSaldo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(75, 75, 75)
                                .addComponent(lblKaryawan))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbCatagtpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCariAnggotaSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFind))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblKaryawan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCatagtpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCariAnggotaSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAnggotaSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAnggotaSimpanMouseClicked
        // TODO add your handling code here:
        int row = tblAnggotaSimpan.getSelectedRow();

        txtkdAnggotaSimpan.setText(tblAnggotaSimpan.getValueAt(row, 0).toString());
        txtkdAnggota.setText(tblAnggotaSimpan.getValueAt(row, 1).toString());
        txtNominal.setText(tblAnggotaSimpan.getValueAt(row, 3).toString());
        txtNominal.setEnabled(false);
        btnEdit.setEnabled(true);
        btnSave.setEnabled(false);
    }//GEN-LAST:event_tblAnggotaSimpanMouseClicked

    private void cmbCatagtpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCatagtpinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCatagtpinjamActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        SearchTable(cmbCatagtpinjam.getSelectedItem().toString(), txtCariAnggotaSimpan.getText());
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        boolean flag = this.anggotaSimpanController.save(txtkdAnggotaSimpan.getText(), txtkdAnggota.getText(), lblKaryawan.getText(), txtNominal.getText());
        String message = "Failed to save data";
        if (flag) {
            message = "succes save";
        }
        JOptionPane.showMessageDialog(this, message, "Allert/Notification", JOptionPane.INFORMATION_MESSAGE);
        bindingTable();
        cekSaldo();
        reset();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:

        String message = "Failed to edit data";
        if (anggotaSimpanController.edit(txtkdAnggotaSimpan.getText(), txtkdAnggota.getText(), lblKaryawan.getText(), txtNominal.getText())) {
            message = "Succes to edit data";
        }
        JOptionPane.showMessageDialog(this, message, "Notification", JOptionPane.ERROR_MESSAGE);
        bindingTable();
        cekSaldo();
        reset();
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSaldoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSaldoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbCatagtpinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblKaryawan;
    private javax.swing.JTable tblAnggotaSimpan;
    private javax.swing.JTable tblSaldo;
    private javax.swing.JTextField txtCariAnggotaSimpan;
    private javax.swing.JTextField txtNominal;
    private javax.swing.JTextField txtkdAnggota;
    private javax.swing.JTextField txtkdAnggotaSimpan;
    // End of variables declaration//GEN-END:variables
public void cekSaldo() {
        String[] header = {"Jumlah Saldo"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
        for (Simpanan simpanan : simpananController.binding()) {
            Object[] region1 = {
                simpanan.getTotalSimpan()
            };
            defaultTableModel.addRow(region1);
        }

        tblSaldo.setModel(defaultTableModel);
    }

    public void bindingTable() {

        String[] header = {"Kode Anggota Simpan", "kode Anggota", "Tanggal Simpan", "Nominal"};

        DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
        for (AnggotaSimpan anggotaSimpan : anggotaSimpanController.binding()) {
            Object[] region1 = {
                anggotaSimpan.getKdAnggotaSimpan(), anggotaSimpan.getKdAnggota(), anggotaSimpan.getTglSimpan(), anggotaSimpan.getNominal()
            };
            defaultTableModel.addRow(region1);
        }
        tblAnggotaSimpan.setModel(defaultTableModel);

    }

    private void SearchTable(String category, String data) {

        String[] header = {"Kode Anggota Simpan", "Kode Anggota", " Tanggal Simpan", "Nominal"};

        DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
        for (AnggotaSimpan anggotaSimpan : anggotaSimpanController.find(category, data)) {
            Object[] region1 = {
                anggotaSimpan.getKdAnggotaSimpan(), anggotaSimpan.getKdAnggota(), anggotaSimpan.getTglSimpan(), anggotaSimpan.getNominal()
            };
            defaultTableModel.addRow(region1);
        }
        tblAnggotaSimpan.setModel(defaultTableModel);
    }

    private void reset() {
        txtkdAnggotaSimpan.setText("");
        txtkdAnggota.setText("");
        txtNominal.setText("");

    }

}
