/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.AnggotaPinjamController;
import entities.AnggotaPinjam;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tools.MyConnection;

/**
 *
 * @author Gusma
 */
public class AnggotaPinjamView extends javax.swing.JInternalFrame {

    private AnggotaPinjamController anggotaPinjamController;

    /**
     * Creates new form AnggotaPinjamView
     */
    public AnggotaPinjamView(Connection connection) {
        initComponents();
        this.anggotaPinjamController = new AnggotaPinjamController(new MyConnection().getConnection());
        bindingTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAPinjam = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textkdAnggotaP = new javax.swing.JTextField();
        textAnggota = new javax.swing.JTextField();
        textkdKaryawan = new javax.swing.JTextField();
        textNamaJ = new javax.swing.JTextField();
        textTanggal = new javax.swing.JTextField();
        textNominal = new javax.swing.JTextField();
        textJangka = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        textCari = new javax.swing.JTextField();
        cmbAnggotaPinjam = new javax.swing.JComboBox<>();
        btnCari = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        tblAPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAPinjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAPinjam);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Anggota Pinjam"));

        jLabel1.setText("KD AnggotaPinjam");

        jLabel2.setText("KD Anggota");

        jLabel3.setText("KD Karyawan");

        jLabel4.setText("Nama Jaminan");

        jLabel5.setText("Tanggal Pinjam");

        jLabel6.setText("Nominal Pinjam");

        jLabel7.setText("Jangka Waktu");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDrop.setText("Drop");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDrop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNominal, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(textTanggal)
                            .addComponent(textNamaJ)
                            .addComponent(textkdKaryawan)
                            .addComponent(textkdAnggotaP)
                            .addComponent(textAnggota)
                            .addComponent(textJangka))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textkdAnggotaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textkdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textNamaJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textJangka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnEdit)
                    .addComponent(btnDrop))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        cmbAnggotaPinjam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kd_anggotapinjam", "kd_anggota", "kd_karyawan", "nama_jaminan", "tgl_pinjam", "nominal_pinjam", "jangka_waktu" }));
        cmbAnggotaPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAnggotaPinjamActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmbAnggotaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCari, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbAnggotaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari))
                        .addGap(3, 3, 3)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAPinjamMouseClicked
        int row = tblAPinjam.getSelectedRow();
        textkdAnggotaP.setText(tblAPinjam.getValueAt(row, 0).toString());
        textAnggota.setText(tblAPinjam.getValueAt(row, 1).toString());
        textkdKaryawan.setText(tblAPinjam.getValueAt(row, 2).toString());
        textNamaJ.setText(tblAPinjam.getValueAt(row, 3).toString());
        textTanggal.setText(tblAPinjam.getValueAt(row, 4).toString());
        textNominal.setText(tblAPinjam.getValueAt(row, 5).toString());
        textJangka.setText(tblAPinjam.getValueAt(row, 6).toString());
    }//GEN-LAST:event_tblAPinjamMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String category = cmbAnggotaPinjam.getSelectedItem().toString();
        String data = textCari.getText();
        searchTable(category, data);
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        String message = "Failed to drop data..";
        int flag = JOptionPane.showConfirmDialog(this, "Really?", "DELETE?", JOptionPane.YES_NO_OPTION);
        if (flag == 0) {
            if (anggotaPinjamController.drop((textkdAnggotaP.getText()))) {
                message = "Success to drop data";
            }
            JOptionPane.showMessageDialog(this, message, "Notification", JOptionPane.QUESTION_MESSAGE);
        }
        bindingTable();
        reset();
    }//GEN-LAST:event_btnDropActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String message = "Failed to edit data..";
        boolean flag = this.anggotaPinjamController.edit(textkdAnggotaP.getText(),
                textAnggota.getText(), textkdKaryawan.getText(), textNamaJ.getText(), java.sql.Date.valueOf(textTanggal.getText()),
                Integer.parseInt(textNominal.getText()), Integer.parseInt(textJangka.getText()));
        if (flag) {
            message = "Success to save data";
        }
        JOptionPane.showMessageDialog(this, message, "Notification", JOptionPane.INFORMATION_MESSAGE);
        bindingTable();
        reset();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        boolean flag = this.anggotaPinjamController.save(textkdAnggotaP.getText(),
                textAnggota.getText(), textkdKaryawan.getText(), textNamaJ.getText(), java.sql.Date.valueOf(textTanggal.getText()),
                Integer.parseInt(textNominal.getText()), Integer.parseInt(textJangka.getText()));
        String message = "Failed to save data..";
        if (flag) {
            message = "Success to save data";
        }
        JOptionPane.showMessageDialog(this, message, "Notification", JOptionPane.INFORMATION_MESSAGE);
        bindingTable();
        reset();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbAnggotaPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAnggotaPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAnggotaPinjamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbAnggotaPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAPinjam;
    private javax.swing.JTextField textAnggota;
    private javax.swing.JTextField textCari;
    private javax.swing.JTextField textJangka;
    private javax.swing.JTextField textNamaJ;
    private javax.swing.JTextField textNominal;
    private javax.swing.JTextField textTanggal;
    private javax.swing.JTextField textkdAnggotaP;
    private javax.swing.JTextField textkdKaryawan;
    // End of variables declaration//GEN-END:variables
 /**
  * Function to show data from table
  */
    public void bindingTable() {
        String[] header = {"KD AnggotaPinjam", "KD Anggota", "KD Karyawan", "Nama Jaminan", "Tanggal Pinjam", "Nominal Pinjam", "Jangka Waktu"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
        for (AnggotaPinjam anggotaPinjam : anggotaPinjamController.bindingsort("kd_anggotapinjam", "asc")) {
            //for (Region region : regionController.binding("region_id","asc")) {
            Object[] anggotaPinjam1 = {anggotaPinjam.getKdAnggotapinjam(), anggotaPinjam.getKdAnggota(),
                anggotaPinjam.getKdKaryawan(), anggotaPinjam.getNamaJaminan(), anggotaPinjam.getTglPinjam(), anggotaPinjam.getNominalPinjam(),
                anggotaPinjam.getJangkaWaktu()
            };
            defaultTableModel.addRow(anggotaPinjam1);
        }
        tblAPinjam.setModel(defaultTableModel);
    }
    /**
     * function search table
     * @param category String
     * @param data String
     */
    public void searchTable(String category, String data) {
        String[] header = {"KD AnggotaPinjam", "KD Anggota", "KD Karyawan", "Nama Jaminan", "Tanggal Pinjam", "Nominal Pinjam", "Jangka Waktu"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
        for (AnggotaPinjam anggotaPinjam : anggotaPinjamController.find(category, data)) {
            Object[] anggotapinjam1 = {
                anggotaPinjam.getKdAnggotapinjam(), anggotaPinjam.getKdAnggota(),
                anggotaPinjam.getKdKaryawan(), anggotaPinjam.getNamaJaminan(),
                anggotaPinjam.getTglPinjam(), anggotaPinjam.getNominalPinjam(),
                anggotaPinjam.getJangkaWaktu()
            };
            defaultTableModel.addRow(anggotapinjam1);
        }
        tblAPinjam.setModel(defaultTableModel);
    }
    /**
     * function reset data
     */
    public void reset() {
        textkdAnggotaP.setText("");
        textAnggota.setText("");
        textkdKaryawan.setText("");
        textNamaJ.setText("");
        textTanggal.setText("");
        textNominal.setText("");
        textJangka.setText("");
    }
}
