/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.AngsuranPinjamController;
import entities.AngsuranPinjam;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gusma
 */
public class AngsuranPinjamView extends javax.swing.JInternalFrame {

    private Connection connection;
    private ViewProccess viewProccess;
    private AngsuranPinjamController angsuranPinjamController;

    /**
     * Creates new form AngsuranPinjamView
     */
    public AngsuranPinjamView(Connection connection) {
        this.connection = connection;
        initComponents();
        this.angsuranPinjamController = new AngsuranPinjamController(connection);
        bindingTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAngsuran = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textKdangsur = new javax.swing.JTextField();
        textAnggotaP = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        cmbangsuran = new javax.swing.JComboBox<>();
        textCariangsuran = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setClosable(true);
        setTitle("Angsuran");

        tblAngsuran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblAngsuran);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Angsuran Pinjam Details"));

        jLabel1.setText("KD Angsuran");

        jLabel2.setText("KD Anggota Pinjam");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textKdangsur, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(textAnggotaP))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textKdangsur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textAnggotaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addComponent(btnSave)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        cmbangsuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kd_angsuran", "kd_anggotapinjam", "tanggal_angsur", "jumlah_angsuran", "status" }));

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cmbangsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCariangsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbangsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCariangsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       boolean flag = this.angsuranPinjamController.save(textKdangsur.getText(), textAnggotaP.getText());
        String message = "Failed to save data";
        if (flag) {
            message = "succes save";
        }
        JOptionPane.showMessageDialog(this, message, "Allert/Notification", JOptionPane.INFORMATION_MESSAGE);
        bindingTable();
        
        reset();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
    SearchTable(cmbangsuran.getSelectedItem().toString(),textCariangsuran.getText());
        
    }//GEN-LAST:event_btnCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbangsuran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAngsuran;
    private javax.swing.JTextField textAnggotaP;
    private javax.swing.JTextField textCariangsuran;
    private javax.swing.JTextField textKdangsur;
    // End of variables declaration//GEN-END:variables
public void bindingTable() {

        String[] header = {"Kode Angsuran ", "kode Anggota Pinjam", "Tanggal angsuran", "jumlah angsuran","status"};

        DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
        for (AngsuranPinjam angsuranPinjam : angsuranPinjamController.binding()) {
            Object[] region1 = {
                angsuranPinjam.getKdAngsuran(), angsuranPinjam.getKdAnggotaP(), angsuranPinjam.getTglAngsur(), angsuranPinjam.getJumlahAngsuran(),angsuranPinjam.getStatus()
            };
            defaultTableModel.addRow(region1);
        }
       tblAngsuran.setModel(defaultTableModel);

    }
private void SearchTable(String category,String data) {

        String[] header = {"Kode angsuran", "kode anggota pinjam", "tanggal angsur","jumlah angsuran","status"};
        
       
        DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
        for (AngsuranPinjam angsuranPinjam : angsuranPinjamController.find(category ,data)) {
            Object[] region1 = {
                angsuranPinjam.getKdAngsuran(), angsuranPinjam.getKdAnggotaP(),angsuranPinjam.getTglAngsur(),angsuranPinjam.getJumlahAngsuran(), angsuranPinjam.getStatus()
            };
            defaultTableModel.addRow(region1);
        }
        tblAngsuran.setModel(defaultTableModel);
    }
        
  public void reset(){
      textKdangsur.setText("");
      textAnggotaP.setText("");
     
  }
}
